export const COUNTRIES = [
  { code: 'FR', name: 'France', aliases: ['france', 'république française', 'republique francaise'] },
  { code: 'BE', name: 'Belgique', aliases: ['belgique', 'belgium'] },
  { code: 'CH', name: 'Suisse', aliases: ['suisse', 'switzerland'] },
  { code: 'LU', name: 'Luxembourg', aliases: ['luxembourg'] },
  { code: 'MC', name: 'Monaco', aliases: ['monaco'] },

  { code: 'DE', name: 'Allemagne', aliases: ['allemagne', 'germany', 'deutschland'] },
  { code: 'AT', name: 'Autriche', aliases: ['autriche', 'austria', 'österreich', 'osterreich'] },
  { code: 'NL', name: 'Pays-Bas', aliases: ['pays-bas', 'pays bas', 'netherlands', 'holland', 'hollande'] },
  { code: 'ES', name: 'Espagne', aliases: ['espagne', 'spain', 'españa', 'espana'] },
  { code: 'PT', name: 'Portugal', aliases: ['portugal'] },
  { code: 'IT', name: 'Italie', aliases: ['italie', 'italy', 'italia'] },
  { code: 'IE', name: 'Irlande', aliases: ['irlande', 'ireland', 'éire', 'eire'] },
  { code: 'GB', name: 'Royaume-Uni', aliases: ['royaume-uni', 'royaume uni', 'united kingdom', 'uk', 'angleterre'] },
  { code: 'DK', name: 'Danemark', aliases: ['danemark', 'denmark'] },
  { code: 'SE', name: 'Suède', aliases: ['suede', 'suède', 'sweden'] },
  { code: 'NO', name: 'Norvège', aliases: ['norvege', 'norvège', 'norway'] },
  { code: 'FI', name: 'Finlande', aliases: ['finlande', 'finland'] },
  { code: 'IS', name: 'Islande', aliases: ['islande', 'iceland'] },

  { code: 'PL', name: 'Pologne', aliases: ['pologne', 'poland'] },
  { code: 'CZ', name: 'Tchéquie', aliases: ['tchequie', 'tchéquie', 'czechia', 'république tchèque', 'republique tcheque'] },
  { code: 'SK', name: 'Slovaquie', aliases: ['slovaquie', 'slovakia'] },
  { code: 'HU', name: 'Hongrie', aliases: ['hongrie', 'hungary'] },
  { code: 'RO', name: 'Roumanie', aliases: ['roumanie', 'romania'] },
  { code: 'BG', name: 'Bulgarie', aliases: ['bulgarie', 'bulgaria'] },
  { code: 'GR', name: 'Grèce', aliases: ['grece', 'grèce', 'greece'] },
  { code: 'HR', name: 'Croatie', aliases: ['croatie', 'croatia'] },
  { code: 'SI', name: 'Slovénie', aliases: ['slovenie', 'slovénie', 'slovenia'] },
  { code: 'EE', name: 'Estonie', aliases: ['estonie', 'estonia'] },
  { code: 'LV', name: 'Lettonie', aliases: ['lettonie', 'latvia'] },
  { code: 'LT', name: 'Lituanie', aliases: ['lituanie', 'lithuania'] },

  { code: 'US', name: 'États-Unis', aliases: ['etats-unis', 'états unis', 'usa', 'united states', 'united states of america'] },
  { code: 'CA', name: 'Canada', aliases: ['canada'] },
  { code: 'MX', name: 'Mexique', aliases: ['mexique', 'mexico'] },
  { code: 'BR', name: 'Brésil', aliases: ['bresil', 'brésil', 'brazil'] },
  { code: 'AR', name: 'Argentine', aliases: ['argentine', 'argentina'] },

  { code: 'MA', name: 'Maroc', aliases: ['maroc', 'morocco'] },
  { code: 'DZ', name: 'Algérie', aliases: ['algerie', 'algérie', 'algeria'] },
  { code: 'TN', name: 'Tunisie', aliases: ['tunisie', 'tunisia'] },
  { code: 'SN', name: 'Sénégal', aliases: ['senegal', 'sénégal'] },
  { code: 'CI', name: 'Côte d’Ivoire', aliases: ["cote d'ivoire", "côte d'ivoire", 'ivory coast'] },

  { code: 'TR', name: 'Turquie', aliases: ['turquie', 'turkey'] },
  { code: 'IL', name: 'Israël', aliases: ['israel', 'israël'] },
  { code: 'AE', name: 'Émirats arabes unis', aliases: ['emirats arabes unis', 'émirats arabes unis', 'uae', 'united arab emirates'] },
  { code: 'SA', name: 'Arabie saoudite', aliases: ['arabie saoudite', 'saudi arabia'] },

  { code: 'IN', name: 'Inde', aliases: ['inde', 'india', 'bharat'] },
  { code: 'CN', name: 'Chine', aliases: ['chine', 'china', 'zhongguo'] },
  { code: 'JP', name: 'Japon', aliases: ['japon', 'japan', 'nippon'] },
  { code: 'KR', name: 'Corée du Sud', aliases: ['coree du sud', 'corée du sud', 'south korea', 'korea'] },
  { code: 'SG', name: 'Singapour', aliases: ['singapour', 'singapore'] },

  { code: 'AU', name: 'Australie', aliases: ['australie', 'australia'] },
  { code: 'NZ', name: 'Nouvelle-Zélande', aliases: ['nouvelle-zelande', 'nouvelle-zélande', 'new zealand'] },
] as const;

export const CURRENCIES = [
  { code: 'EUR', name: 'Euro', symbol: '€', aliases: ['eur', 'euro', '€'] },
  { code: 'USD', name: 'Dollar américain', symbol: '$', aliases: ['usd', 'dollar', 'dollar americain', 'dollar américain', '$'] },
  { code: 'GBP', name: 'Livre sterling', symbol: '£', aliases: ['gbp', 'livre', 'livre sterling', '£'] },
  { code: 'CHF', name: 'Franc suisse', symbol: 'CHF', aliases: ['chf', 'franc suisse'] },
  { code: 'CAD', name: 'Dollar canadien', symbol: '$', aliases: ['cad', 'dollar canadien'] },
  { code: 'AUD', name: 'Dollar australien', symbol: '$', aliases: ['aud', 'dollar australien'] },
  { code: 'NZD', name: 'Dollar néo-zélandais', symbol: '$', aliases: ['nzd', 'dollar neo zelandais', 'dollar néo-zélandais'] },

  { code: 'JPY', name: 'Yen japonais', symbol: '¥', aliases: ['jpy', 'yen', '¥'] },
  { code: 'CNY', name: 'Yuan renminbi', symbol: '¥', aliases: ['cny', 'yuan', 'renminbi', 'rmb'] },
  { code: 'HKD', name: 'Dollar de Hong Kong', symbol: '$', aliases: ['hkd', 'dollar hong kong'] },
  { code: 'SGD', name: 'Dollar de Singapour', symbol: '$', aliases: ['sgd', 'dollar singapour'] },
  { code: 'KRW', name: 'Won sud-coréen', symbol: '₩', aliases: ['krw', 'won', '₩'] },
  { code: 'INR', name: 'Roupie indienne', symbol: '₹', aliases: ['inr', 'roupie', '₹'] },

  { code: 'SEK', name: 'Couronne suédoise', symbol: 'kr', aliases: ['sek', 'couronne suedoise', 'couronne suédoise'] },
  { code: 'NOK', name: 'Couronne norvégienne', symbol: 'kr', aliases: ['nok', 'couronne norvegienne', 'couronne norvégienne'] },
  { code: 'DKK', name: 'Couronne danoise', symbol: 'kr', aliases: ['dkk', 'couronne danoise'] },
  { code: 'PLN', name: 'Zloty', symbol: 'zł', aliases: ['pln', 'zloty', 'zł'] },
  { code: 'CZK', name: 'Couronne tchèque', symbol: 'Kč', aliases: ['czk', 'couronne tcheque', 'couronne tchèque', 'kč'] },
  { code: 'HUF', name: 'Forint', symbol: 'Ft', aliases: ['huf', 'forint'] },
  { code: 'RON', name: 'Leu roumain', symbol: 'lei', aliases: ['ron', 'leu', 'lei'] },
  { code: 'BGN', name: 'Lev bulgare', symbol: 'лв', aliases: ['bgn', 'lev'] },

  { code: 'TRY', name: 'Livre turque', symbol: '₺', aliases: ['try', 'lire turque', '₺'] },
  { code: 'ILS', name: 'Nouveau shekel israélien', symbol: '₪', aliases: ['ils', 'shekel', '₪'] },
  { code: 'AED', name: 'Dirham des ÉAU', symbol: 'د.إ', aliases: ['aed', 'dirham', 'uae dirham'] },
  { code: 'SAR', name: 'Riyal saoudien', symbol: '﷼', aliases: ['sar', 'riyal'] },

  { code: 'MAD', name: 'Dirham marocain', symbol: 'د.م.', aliases: ['mad', 'dirham marocain'] },
  { code: 'DZD', name: 'Dinar algérien', symbol: 'دج', aliases: ['dzd', 'dinar algerien', 'dinar algérien'] },
  { code: 'TND', name: 'Dinar tunisien', symbol: 'د.ت', aliases: ['tnd', 'dinar tunisien'] },
  { code: 'XOF', name: 'Franc CFA (BCEAO)', symbol: 'CFA', aliases: ['xof', 'franc cfa', 'cfa'] },
  { code: 'XAF', name: 'Franc CFA (BEAC)', symbol: 'FCFA', aliases: ['xaf', 'franc cfa', 'fcfa'] },

  { code: 'BRL', name: 'Réal brésilien', symbol: 'R$', aliases: ['brl', 'real', 'réal', 'r$'] },
  { code: 'MXN', name: 'Peso mexicain', symbol: '$', aliases: ['mxn', 'peso mexicain'] },
] as const;
